FROM node:20-alpine

WORKDIR /cv

COPY ./package*.json ./

RUN npm install

COPY . .

# Expone el puerto 3000
EXPOSE 3000

# Ejecuta el comando para iniciar la aplicación Next.js
CMD ["npm", "run", "dev"]